### ISSUE TITLE
Complete B.9.0.1.0.02 Curriculum Minutes

### ISSUE THREAD

**Issue by trainfarb** [trainfarb/B.0.9-Onboarding-Platform#41]
> Goal: Teach 144 people how to create minutes for a curriculum that will help them earn $144,000 a year by **focusing** on **slow productivity** to 12x their **creativity**.

- Upload video of creating GitHub Project to YouTube
- Work through Meeting Minutes markdown draft below to talk through how it relates to agenda (still figuring out the progression from agenda to minutes in a clear way)

```
longPlay: hu3_lp0polymathProcess
epicPlaylist: hu3_lp0ep0daoTeaching
verse: hu3_lp0ep0v0ourSource
  description: How to create your community training platform in 27 days with an open source CHRO/ decentralized b0education institution
groove: hu3_lpep0v0gr1ego
  description: How to create a focused ego development curriculum for your community training platform
beat: hu3_lp0ep0v0gr1b9language
  by: trainfarb
  description: Create a focused ego development curriculum for your open source (CLO) onboarding platform/ decentralized b9language institution
phase:
  OWNER: A.2.7.2 Minutes (oS3 BuJo workShop)
  PRODUCER: **B.0.9.2 Documentation (GitHub Project)**
  PROVIDER: B.9.0.2 Unit Plans (Framer Civil Chain Process)
  CONSUMER: C.1.8.2 Agreements (Substack Podcast Recording)
```
# Minutes/ *Documentation/ Unit Plan/ Agreement
## Goal and Agents
`What is the primary goal for this cohort based course?`
* Goal: hu3_lp0ep0v0gr1b9language - Create ego development focused curriculum for an open source (CLO) Onboarding Platform
`Who are the agents, and what are their supporting goals?`
* Agents:
  * OWNER: DEG - BuJo workSheet/Book/Shop/Pad
  * PRODUCER: trainfarb - GitHub Org/Repo/Project/Discussion
  * PROVIDER: hu3agency - Framer Home/Supply/Civil/Value Chains
  * CONSUMER: ourStory - Wallet Profile/Post/Podcast/Video
> Added code snippets as questions and clarified goals for each agent

## Problem Formulation: Initial State
`Define Initial State of the problem to explain why help is needed`
* Initial State: 
  * Minutes Response (trainfarb): **Wellness Center Property Managers** don’t have the resources to hire an experienced **Chief Language Officer (CLO)** for an effective **Onboarding** Platform, so centralized **b9language** institutions maintain power and control.
    * From Agenda: Wasted energy developing 12 different curricula limits creative output of each team 
`What questions add context to these challenges?`
* Questions
  * PRODUCER: What are 3 Initial State Challenges that MSMEs face without a **Chief Language Officer (CLO)**?
    * From Agenda: Each team has an unfocused training platform
    * 2
    * 3
  * PROVIDER: What are 3 Initial State Advantages that Institutions have with a **Chief Language Officer (CLO)**?
    * From Agenda: Each team has to create their own training curriculum which is unproductive
    * 2
    * 3
  * CONSUMER: What are 3 examples that highlight the gap between MSMEs and Institutions because of **CLOs**?
    * From Agenda: Wasted energy developing 12 different curricula limits creative output of each team
    * 2
    * 3
> Add questions that give whoever is assigned this section a place to start, and migrate initial items from agenda as primer responses.

## Problem Formulation: Actions
`Outline actions that we believe will overcome the initial state challenges`
* Action: 
  * Minutes Response (trainfarb): How can **trainfarb** form a decentralized **b9language** institutions so **Wellness Center Property Managers** can benefit from the network effects of an open source **Chief Language Officer (CLO)** community platform?
`What questions add context to build up the curriculum?`
* Questions
  * PRODUCER: What are 3 negative traits of a centralized **b9language** institution?
    * 1
    * 2
    * 3
  * PROVIDER: What are 3 positive traits of a decentralized **b9language** institution?
    * 1
    * 2
    * 3
  * CONSUMER: What are 3 examples that highlight the disparity between centralized and decentralized **b9language** institutions?
    * 1
    * 2
    * 3

## Searching Solution: Transition Model
`How will you turn the problem into an ego development curriculum?`
* Transition Model Curriculum: Teach people how to relate a **B.0.9 Onboarding** Platform, Open Source **Chief Language Officer (CLO)**, and decentralized **b9language** institution to the human **Integumentary System** so **Wellness Center Property Managers** can learn how to internalize the benefits.
`What questions add context to build up the curriculum?`
* Questions:
  * PRODUCER: What are 3 challenges of an unconscious ego that are similar to centralized **b9language** institutions
    * 1
    * 2
    * 3
  * PROVIDER: What are 3 benefits of a conscious ego that are similar to decentralized **b9language** institutions
    * 1
    * 2
    * 3
  * CONSUMER: What are 3 ways conscious ego benefits can be applied to personal development?
    * 1
    * 2
    * 3

## Searching Solution: Path Cost
`How does this curriculum describe the value of this cohort based course?`
* Path Cost: How to Create an Open Source **Chief Language Officer (CLO)** **Onboarding** Platform Curriculum by focusing on slow productivity to 12x their creative output. Teach people how to relate a **B.0.9 Onboarding Platform**, Open Source **Chief Language Officer (CLO)**, Decentralized **b9language** institution, and human **integumentary system** to a eukaryotic cell **membrane** to create a first principles biomimicry mental model that can be applied to any project they have in the future.
  * PRODUCER: $117.8571: How to create a curriculum agenda GitHub Repository.
  * PROVIDER: $428.571: How to create curriculum minutes GitHub Project
  * CONSUMER: $12.8571: How to create curriculum debrief with GitHub Discussions
> All of these are GitHub related because this is for trainfarb (PRODUCER)

## Executing Actions: Solution
`How will you share your solution?`
* Create ongoing essays that relates this cohort based course to the planet based on our theoretical framework
  * Focus on personal flaws instead of the flaws of others
  * Cell inspired slow productivity for personal growth
  * Creatively adapt personal plan for institutions using an open source model of a self-sovereign city block

## Executing Actions: Optimal Solution
`How will you creatively share your story?`
* OWNER: Meeting/Training/Onboarding Memo to define creative universe to build a world based on the **Universal Chakra** (**174 Hz**) inspired by solar punk.
  * PRODUCER: Meeting/Training/**Onboarding** Agenda builds the creative world as a parallel reality to our own
  * PROVIDER: Meeting/Training/**Onboarding** Minutes develop the setting as a 1-to-1 relationship with the actions we take with our platform ecosystems
  * CONSUMER: Meeting/Training/**Onboarding** Debrief forms creative narrative that uses Haiti as an open source model for how we expand creative freedom around the world and universe.

## Summary
`How do we summarize the curriculum for this cohort based course?`
* Summary
  * Problem formulation: Create Agenda & Publish Repo
  * Searching Solution: Develop GitHub Project
  * Executing Actions: Complete Tasks & Share Story
