### ISSUE TITLE
Complete B.9.0.1.0.03 Curriculum Debrief

### ISSUE THREAD

**Issue by trainfarb** [trainfarb/B.0.9-Onboarding-Platform#42]
> Goal: Teach 144 people how to create a curriculum debrief that will help them earn $144,000 a year by increasing their **focusing** with **slow productivity** to 12x their **creative** output.

Complete the BuJo A3 Debrief Draft ahead of the rest of the steps to explain how we want things to play out. Use meeting minutes markdown as a guide for how it all plays out in the debrief draft.

```
longPlay: hu3_lp0polymathProcess
  description: lp0_polymathProcess is the B.9.0 Training Platform/b0education institution for hu3agency
epicPlaylist: hu3_lp0ep0daoTeaching
  description: ep0_daoTeaching is the 12-month project by lp0_polymathProcess focused on teaching Wellness Center Owner’s Representatives platform design engineering.
verse: hu3_lp0ep0v0ourSource
  description: v0ourSource is a 28 day Curriculum that teaches how to create a B.9.0 Training Platform/ Open Source CHRO/ Decentralized b0education institution
groove: hu3_lp0ep0v0gr1ego
  description: v0gr1ego is an 8-day Unit Plan that teaches how to create a focused ego development curriculum for your community training platform
beat: hu3_lp0ep0v0gr1b9language
  by: trainfarb
  description: v0gr1b1language is a 1-day Lesson Plan that teaches how to create a focused ego development curriculum for your B.0.9 Onboarding Platform/ Open Source (CLO)/ Decentralized b9language Institution
phase:
  OWNER: **A.2.7.3 Debrief (A3 BuJo workPad)**
  PRODUCER: B.0.9.3 Models (GitHub Discussion)
  PROVIDER: B.9.0.3 Lesson Plans (Framer Value Chain Process)
  CONSUMER: C.1.8.3 Wallets (Substack Video Recording)
```

# *Debrief/ Model/ Lesson Plan/ Wallet
## YOU
`What did we create yesterday?`
Finalize workSheet, workBook, workShop, and workPad for ourStory’s Training Platform (https://github.com/orgs/hu3agency/projects/25/views/7?pane=issue&itemId=56634335)

`What concerns are valid after what we created?`
How can these idealistic notes be turned into a valuable Training Platform that realistically 12x’s people’s creative output?

`How will we address this concern today?`
Develop trainfarb’s Onboarding Process for any ourStory.network Curriculum

## NEED
`What’s the focus for today?`
Publish trainfarb’s B.0.9 Onboarding Curriculum to GitHub Repository

`What slow productivity tools will we use to track today’s progress?`
GitHub Project: [tf] B.9.0.1 Training Platform Curriculum

`What’s the creativity tool used?`
A3 BuJo workPad

## GO
`What memo did we create?`
trainfarb’s Onboarding Memo: #39 

`What challenge did we experience?`
How do we standardize this so others can 12x their creative output when developing all of the curriculums for their platform?

`How was this resolved?`
Record video walkthrough creating a standardized markdown format for GitHub Orgs and upload to YouTube

## SEARCH
`What agenda did we create?`
trainfarb’s Onboarding Curriculum Agenda: #40 

`What challenge did we experience?`
How do we create a curriculum agenda if we still haven’t finalized the standard agenda process? We made progress with the agenda in the past month, but it has changed each day as we refine and learn what we want to do. A.2.7.1 Agenda lines up with B.9.0.1 Curriculum, so the curriculum is meant to be a derivative of the agenda. Without a clear strategy for the agenda, what we create for the curriculum wouldn’t have a strong foundation.

`How was this resolved?`
Adapt “Solving Problems by Searching” research PDF for AI for the A.2.7.1 Agenda process. B.0.9.1 Problems (also associated with Agendas) is based in AI Problem Formulation. When I searched for AI Problem formulation to come up with a more clear format that could potentially be applied to both the agenda and curriculum, I found a structure that worked.

## FIND
`What minutes did we create?`
trainfarb’s Onboarding Curriculum Minutes: #41 

`What challenge did we experience?`
How do the minutes relate to the agendas (new format) in a practical way so that it’s easy to teach people how to create a curriculum for themselves? 

`How was this resolved?`
Yesterday’s agenda from ourStory (https://github.com/orgs/hu3agency/projects/25/views/7?pane=issue&itemId=56634335) is what will naturally evolve into today’s B.9.0.1 Curriculum format. We broke down the notes from yesterday’s agenda (curriculum outline) into a 32 step GitHub Project so it’s easier to learn and implement.

## TAKE
`What debrief are we creating?`
trainfarb’s Onboarding Curriculum Debrief: (This issue)

`What challenge are we anticipating?`
This is our first time working through a 32-step GitHub Project for a 1-day lesson plan in this way, so it’s going to take longer than a day (writing this on day 2 already). I get mentally drained when working on a process because I try to think of how it can be as simple as possible for others. This is really the fist time I’m creating a step by step lesson plan for someone, so it’ll take a while.

`How will this be resolved?`
This 1-day lesson plan is part of an 8-day unit plan. The only thing that I HAVE to do is complete this in 8 days. The ideal scenario is that I complete all 12 platform 1-day lesson plans for creating a curriculum in these 8-days, but that’s unrealistic because a lot of the set up work (finalizing the agenda format, determining how to structure the 1-day GitHub Project, etc.) all took away from what will be much faster in the future. The resolution is writing out these challenges in this debrief so I can work through them within this Quantum Pincer Movement and find ways to improve my efficiency as I go to increase the value that I can provide people in the future when this is a live course that I’m helping others work through.

## RETURN
`Lesson learned from agenda?`
AI Problem Solving Agents will provide answers for how we approach Agendas and all of the X.X.1 sections for each platform moving forward:
- A.2.7.1 Agendas
  - B.0.9.1 Problems
  - B.9.0.1 Curriculum
  - C.1.8.1 Goals
  - D.8.1.1 Work Breakdown Structures
  - E.7.2.1 Research
  - F.6.3.1 Risks
  - G.5.4.1 Proposals
  - H.4.5.1 Theories
  - I.3.6.1 Builds

`Lesson learned from minutes?`
Meeting minutes as GitHub Projects is a really practical way to track meetings because it already has all of the different sections/team responsibilities split up into a minimum of 32 distinct issues that each of them can manage and use to communicate through the resolution. Atomizes meeting minutes.

`Lesson learned from debrief?`
Debriefs should be drafted before getting to work in a 1-day lesson plan so we have a clear idea of what challenges that we should anticipate. This will get easier and easier with time and save a lot of energy.

## CHANGED
`What did we create today?`
Develop trainfarb’s Onboarding Process for any ourStory.network Curriculum

`What concerns does this bring up?`
This is meant to be a process that any other platform team can use, but how do we know it will actually work for the different context of each team? How can we prove this will 12x the output for anyone who needs to create a 12-month curriculum?

`How will we address this tomorrow?`
Apply the process created today to hu3agency’s B.9.0 Training Platform’s curriculum and Health Intention’s D.8.1 Management Platform’s curriculum. Track the time for each to see how much faster they were completed compared to today?
